#!/bin/bash

if [ -d ~/.schism ]
then
echo "$(basename ${0}) ${@}" >> ~/.schism/schism_history
fi

if [ $1 == "init" ];
then
    if [ -d ~/.schism ]
    then
        echo "~/.schism already exists"
    else
        mkdir ~/.schism
    fi
    if [ -d ~/.schism/time ]
    then
        echo "~/.schism/time already exists"
    else
        mkdir -p ~/.schism/time
    fi

fi

if [ $1 == "play" ];
then
while true;
do

play ~/Music/Bash/BlasterMaster7.ogg
play ~/Music/Bash/SuperMario3BowserBattle.mp3
play ~/Music/Bash/WilyFortress.mp3

done
fi

if [ $1 == "clean" ];
then

ls -Q ~/Music/Bash/Warcraft\ II/* | xargs play

fi

if [ $1 == "ed" ];
then

cd ~/.schism/time
ed "${2}"
fi
