#!/bin/bash

if [ -d ~/.schism ]
then
echo "$(basename ${0}) ${@}" >> ~/.schism/schism_history
date +%s >> ~/.schism/schism_history
fi

if [ $1 == "init" ];
then
    if [ -d ~/.schism ]
    then
        echo "~/.schism already exists"
    else
        mkdir ~/.schism
    fi
    if [ -d ~/.schism/time ]
    then
        echo "~/.schism/time already exists"
    else
        mkdir -p ~/.schism/time
    fi

fi

if [ $1 == "play" ];
then
    shift
    schism-play ${@}
    exit 0
fi

if [ $1 == "ed" ];
then
    shift
    schism-ed ${@}
    exit 0
fi
