#!/bin/bash
date="`date +%Y-%m-%d`"

if [ $# -eq 0 ]
then
    ed "freewrite-`date`.txt"

elif [ $1 == "todo" ]
then
    cp ~/.schism/ed/templates/todo.yml ~/.schism/ed/todo/todo$date.yml
    ed ~/.schism/ed/todo/todo$date.yml

elif [ $1 == "reflection" ]
then
    cp ~/.schism/ed/templates/reflection.yml ~/.schism/ed/reflection/reflection$date.yml
    ed ~/.schism/ed/reflection/reflection$date.yml

else
    ed ${@}
fi
