#!/bin/bash

home_dir='~/.schism/play'

if [ $# -eq 0 ]
then

while true;
do
    play "$home_dir/BlasterMaster7.ogg" "$home_dir/SuperMario3BowserBattle.mp3" "$home_dir/WilyFortress.mp3";
done

fi

case $1 in
    clean)
        find ~/.schism/play/WarcraftII -name '*.ogg' -print0 | sort -z | xargs -0 play
        ;;
    relax)
        while true; do play $home_dir/relax.mp3; done
        ;;
    upbeat)
         ls -Q ~/.schism/play/Upbeat/*.mp3 | xargs play
        ;;
    humor)
        find -L ~/.schism/play/Humor -name '*.mp3' -print0 | sort -Rz | xargs -0 play
        ;;
    wakeup)
        while true
            do
                play "$home_dir/wakeup.mp3"
                echo -e $(cat ~/.schism/reminders/wakeup.txt)
            done
        ;;
    victory)
        ls ~/.schism/play/Victory/FF*.mp3 | sort -R | head -1 | xargs play
        ;;
    sleep)
        while true; do play $home_dir/sleep.mp3; done
        ;;
    malinche)
        audiodisk=$(( $RANDOM % 5 ))
        cd /home/jginns/Libros\ En\ Español/Laura\ Esquivel/Malinche/Disk\ $audiodisk/
        lines=`ls *.mp3 | wc -l`
        cutlength=$((lines - $1))
        ls -Q *.mp3 | sort | tail -n $cutlength | xargs play
        ;;
    *)
        echo "current choices are: clean, relax, upbeat, humor, wakeup, sleep, and malinche"
        ;;
esac
